import { LanguageOption } from '@/utils/type';
export const TentangAnime: Record<LanguageOption, string[]> = {
     indonesia: [
          "Shigatsu wa Kimi no Uso (Your Lie in April) adalah sebuah anime romantis yang mengisahkan perjalanan emosional seorang pianis jenius bernama Kousei Arima. Setelah kehilangan ibunya yang juga merupakan guru pianonya, Kousei mengalami trauma yang membuatnya tidak bisa mendengar suara piano lagi meskipun pendengarannya normal.",
          "2 Tahun lamanya Kousei tidak memainkan piano dan ia mulai merasa jenuh dan hidupnya kurang berwarna,walaupun begitu ia selalu ditemani Tsubaki dan Watari,teman dekatnya yang selalu peduli pada dirinya.Suatu hari Watari memberitahukan bahwa ia mempunyai pacar baru ,yaitu Mizayono Kaori ,seorang pemain violin/biola yang cantik yang rupanya Kousei menaruh hati padanya juga.",
          "Kousei menahan diri karena Watari adalah sahabatnya.Sejak saat itu Kaori juga dekat dengan Kousei.Kaouri mengetahui bahwa Kousei adalah mantan juara kompetisi piano,oleh karena itu ia selalu menyemangati Kousei untuk bermain piano lagi,bahkan ia mengajak Kousei untuk menjadi pianist pengiringnya.Kousei dituntut agar ia bermain piano sebebas bebasnya tidak seperti gaya bermain pianonya dahulu.",
          "Sementara itu, hubungan antara Kousei, Kaori, Tsubaki, dan teman mereka Ryouta Watari menjadi lebih kompleks. Tsubaki mulai menyadari perasaannya terhadap Kousei, sementara Kaori tampaknya tertarik pada Watari. Seiring berjalannya waktu, terungkap bahwa Kaori menderita penyakit yang tidak disebutkan namanya, yang membuatnya sering masuk rumah sakit. Meskipun begitu, dia terus mendorong Kousei untuk bermain piano dan mengikuti kompetisi.",
          "Singkat Cerita, Kaori yang bermimpi menggesek dawai biola diatas panggung bersama arima kousei akhirnya harus berakhir dimeja operasi. Detak jantung Kaori perlahan melambat dan kemudian berhenti selamanya diatas meja operasi itu. Meninggalkan kenangan yang amat mendalam, bukan hanya bagi Kousei, tapi juga bagi Wattari dan Tsubaki yang belakangan memang selalu menghabiskan waktu bersama-sama. Miyazono Kaori akhirnya telah pergi untuk selamanya.",
          "Dan yang terakhir, mengenai judul Shigatsu wa Kimi no Uso yang dapat diartikan “Kebohonganmu di Bulan April” diambil dari adegan saat pertama kalinya Kaori dan Kousei bertemu di musim semi, tepatnya di bulan April, di mana Kaori mengatakan kalau dirinya menyukai Watari, padahal … yang sebenarnya dia sukai adalah Kousei sendiri."
     ],
     inggris: [
          "Shigatsu wa Kimi no Uso (Your Lie in April) is a romantic anime that tells the emotional journey of a piano prodigy named Kousei Arima. After losing his mother, who was also his piano teacher, Kousei experiences trauma that prevents him from hearing the sound of the piano even though his hearing is normal.",
          "For 2 years, Kousei didn't play the piano and began to feel bored and that his life lacked color, although he was always accompanied by Tsubaki and Watari, his close friends who always cared for him. One day, Watari informs him that he has a new girlfriend, Mizayono Kaori, a beautiful violinist who Kousei also develops feelings for.",
          "Kousei holds back because Watari is his best friend. Since then, Kaori also becomes close to Kousei. Kaori learns that Kousei is a former piano competition champion, so she always encourages Kousei to play the piano again, even inviting him to be her accompanist. Kousei is challenged to play the piano as freely as possible, unlike his former piano playing style.",
          "Meanwhile, the relationship between Kousei, Kaori, Tsubaki, and their friend Ryouta Watari becomes more complex. Tsubaki begins to realize her feelings for Kousei, while Kaori seems interested in Watari. As time goes by, it is revealed that Kaori suffers from an unnamed illness, which causes her to be hospitalized frequently. Despite this, she continues to encourage Kousei to play the piano and participate in competitions.",
          "In short, Kaori, who dreamed of playing the violin on stage with Arima Kousei, ultimately ends up on the operating table. Kaori's heartbeat slowly slows down and then stops forever on that operating table. Leaving a profound memory, not only for Kousei but also for Wattari and Tsubaki who had recently been spending time together. Miyazono Kaori has finally gone forever.",
          "And finally, regarding the title Shigatsu wa Kimi no Uso, which can be translated as 'Your Lie in April,' it is taken from the scene when Kaori and Kousei first meet in spring, specifically in April, where Kaori says that she likes Watari, when in fact... the one she really likes is Kousei himself."
        ],
        romaji: [
          "Shigatsu wa Kimi no Uso wa, tensai pianisuto no Arima Kousei no kanjō-teki na tabi o egaku romanchikku na anime desu. Kare no haha de ari, piano no sensei demo atta hito o nakushita ato, Kousei wa torauma ni nayamasare, chōkaku wa futsū nanoni piano no oto ga kikoenakunarimashita.",
          "2-Nen-kan, Kousei wa piano o hikazu, seikatsu ni iro ga naku taikutsu ni kanjiru yō ni narimashita. Shikashi, itsumo kare no koto o ki ni kakete iru shin'yū no Tsubaki to Watari ga soba ni imashita. Aru hi, Watari wa atarashī kanojo ga dekita to tsutaemashita. Sore wa utsukushī baiorinisuto no Mizayono Kaori de, Kousei mo kanojo ni kokoro o hikaremashita.",
          "Kousei wa Watari ga shin'yūdearu tame ni jibun no kimochi o osaemasu. Sono toki kara, Kaori mo Kousei to shitashiku narimashita. Kaori wa Kousei ga moto piano konkūru no yūshōshadearu koto o shiri, kare ni futatabi piano o ensō suru yō ni hagemashimashita. Kaori wa Kousei ni jibun no akanbanisutonaru koto o susumemashita. Kousei wa, mae no yō ni katakuna de wa naku, jiyū ni piano o ensō suru yō ni motomeraremashita.",
          "Sono aida ni, Kousei, Kaori, Tsubaki, soshite karera no yūjin de aru Ryouta Watari no kankei wa yori fukuzatsuka shimashita. Tsubaki wa Kousei e no omoi ni kidzuki hajime, Kaori wa Watari ni kyōmi o motte iru yō ni miemashita. Jikan to tomo ni, Kaori ga meishō no nai byōki ni kakatte iru koto ga akiraka ni narimashita. Kore ga, kanojo ga hinpan ni nyūin suru riyū deshita. Sore ni mo kakawarazu, kanojo wa Kousei ni piano o ensō shi, konkūru ni sanka suru yō ni hagemashi tsuzukemashita.",
          "Mijikaku ieba, Arima Kousei to butai de baiorin o ensō suru yume o motte ita Kaori wa, saigo ni wa shujutsu-dai de inochi o owarimashita. Kaori no shinzō no kodō wa yukkuri to ososhinari, sono shujutsu-dai de eien ni tomatta no desu. Kore wa Kousei dake de naku, saikin issho ni jikan o sugoshite ita Wattari to Tsubaki ni mo fukai kioku o nokoshimashita. Miyazono Kaori wa tsui ni eien ni saratte shimatta no desu.",
          "Saigo ni, 'Shigatsu wa Kimi no Uso' to iu taitoru ni tsuite desu ga, kore wa 'Shigatsu no Anata no Uso' to yakuseru koto ga dekimasu. Kono taitoru wa, Kaori to Kousei ga hajimete deatta haru no hi, toku ni shigatsu no hi ni, Kaori ga jibun wa Watari ga suki da to itta shīn kara tora rete imasu. Shikashi jissai wa... Kaori ga hontō ni suki datta no wa Kousei jishin datta no desu."
        ],
        kanji: [
          "四月は君の嘘（ヨア・ライ・イン・エイプリル）は、天才ピアニストの有馬公生の感情的な旅を描くロマンチックなアニメです。彼の母であり、ピアノの先生でもあった人を失った後、公生はトラウマに悩まされ、聴覚は普通なのにピアノの音が聞こえなくなりました。",
          "2年間、公生はピアノを弾かず、生活に色がなく退屈に感じるようになりました。しかし、いつも彼のことを気にかけている親友の椿とワタリがそばにいました。ある日、ワタリは新しい彼女ができたと伝えました。それは美しいバイオリニストの宮園かをりで、公生も彼女に心を惹かれました。",
          "公生はワタリが親友であるため自分の気持ちを抑えます。その時から、かをりも公生と親しくなりました。かをりは公生が元ピアノコンクールの優勝者であることを知り、彼に再びピアノを演奏するように励ましました。かをりは公生に自分のアカンパニストになることを勧めました。公生は、前のように頑なではなく、自由にピアノを演奏するように求められました。",
          "その間に、公生、かをり、椿、そして彼らの友人である涼太ワタリの関係はより複雑化しました。椿は公生への想いに気づき始め、かをりはワタリに興味を持っているように見えました。時間とともに、かをりが名称のない病気に罹っていることが明らかになりました。これが、彼女が頻繁に入院する理由でした。それにもかかわらず、彼女は公生にピアノを演奏し、コンクールに参加するように励まし続けました。",
          "短く言えば、有馬公生と舞台でバイオリンを演奏する夢を持っていたかをりは、最後には手術台で命を終えりました。かをりの心臓の鼓動はゆっくりと遅くなり、その手術台で永遠に止まったのです。これは公生だけでなく、最近一緒に時間を過ごしていたワタリと椿にも深い記憶を残しました。宮園かをりはついに永遠に去ってしまったのです。",
          "最後に、「四月は君の嘘」というタイトルについてですが、これは「4月のあなたの嘘」と訳せることができます。このタイトルは、かをりと公生が初めて出会った春の日、特に4月の日に、かをりが自分はワタリが好きだと言ったシーンから取られています。しかし実際は...かをりが本当に好きだったのは公生自身だったのです。"
        ],
        jawa: [
          "Shigatsu wa Kimi no Uso (Gorohmu ing Wulan April) iku anime romantis sing nyritakake lelakone pianis pinter jenenge Kousei Arima. Sawise kelangan ibune sing uga dadi guru pianone, Kousei ngalami trauma sing marakake dheweke ora bisa krungu swara piano maneh sanajan pendengarane normal.",
          "Nganti 2 taun suwene Kousei ora nabuh piano lan uripe krasa bosen lan kurang werna, nanging dheweke tansah dibarengi Tsubaki lan Watari, kanca-kancane sing tansah peduli marang dheweke. Ing sawijining dina, Watari ngabari yen dheweke duwe pacar anyar, yaiku Mizayono Kaori, violinis ayu sing uga narik kawigaten Kousei.",
          "Kousei nahan rasa atine amarga Watari iku kancane dhewe. Wiwit kuwi Kaori uga dadi cedhak karo Kousei. Kaori ngerti yen Kousei iku mantan juara lomba piano, mulane dheweke tansah nyemangati Kousei supaya main piano maneh, malah ngajak Kousei dadi pianis pengirine. Kousei dituntut supaya main piano kanthi luwes, ora kaya cara main pianone sing biyen.",
          "Ing wektu kuwi, hubungane Kousei, Kaori, Tsubaki, lan kancane Ryouta Watari dadi luwih kompleks. Tsubaki wiwit sadhar marang rasa tresnane marang Kousei, dene Kaori ketoke tertarik marang Watari. Saya suwe, kebukak yen Kaori nandhang penyakit sing ora disebutake jenenge, sing marakake dheweke kerep mlebu rumah sakit. Senajan mangkono, dheweke tetep nyemangati Kousei supaya main piano lan melu lomba.",
          "Cekake crita, Kaori sing ngimpi nabuh biola ing panggung bareng Arima Kousei pungkasane kudu mati ing meja operasi. Denyut jantunge Kaori alon-alon saya alon lan banjur mandheg salawase ing meja operasi kuwi. Ninggalake kenangan sing jero, ora mung kanggo Kousei, nanging uga kanggo Wattari lan Tsubaki sing wis suwe ngliwati wektu bareng-bareng. Miyazono Kaori wis lunga salawase.",
          "Lan sing pungkasan, ngenani irah-irahan Shigatsu wa Kimi no Uso sing bisa ditegesi 'Gorohmu ing Wulan April' dijupuk saka adegan nalika sepisanan Kaori lan Kousei ketemu ing mangsa semi, luwih temtu ing wulan April, ing ngendi Kaori ngomong yen dheweke seneng Watari, nanging... sejatine sing disenengi yaiku Kousei dhewe."
        ],
};
